In [109]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style("white")

In [76]:
df = pd.read_csv("ab40c054-5031-4376-b52e-9813e776f65e.csv")

In [110]:
df.describe()

,Andhra Pradesh,Arunachal Pradesh,Assam,Bihar,Chhattisgarh,Goa,Gujarat,Haryana,Himachal Pradesh,Jammu & Kashmir,...,Telangana,Tripura,Uttar Pradesh,Uttarakhand,West Bengal1,Andaman & Nicobar Islands,Chandigarh,Delhi,Puducherry,All_India GDP
count,11.000000,9.000000,9.000000,9.000000,11.000000,9.000000,9.000000,11.000000,7.000000,9.000000,...,11.000000,7.000000,9.000000e+00,9.000000,0.0,7.000000,9.000000,11.000000,11.000000,1.100000e+01
mean,280986.561818,8201.516667,100018.167778,181565.673333,120748.879091,22450.120000,448568.674444,228667.271818,50673.064286,53343.001111,...,268570.787273,13739.691429,5.209237e+05,82588.947778,NaN,2759.814286,13707.002222,258693.004545,12527.435455,6.479952e+06
std,282573.532407,8073.276061,97589.497456,178700.497677,120928.480448,21443.429799,438025.627165,228195.895576,48384.121107,51712.668467,...,268734.549079,13240.797263,5.087288e+05,80553.858327,NaN,2627.016700,13399.003286,258176.516280,12445.889343,6.433000e+06
min,8.430000,12.070000,9.560000,10.590000,10.980000,-10.020000,10.820000,9.180000,10.140000,4.700000,...,11.700000,12.780000,1.051000e+01,8.120000,NaN,10.890000,8.840000,10.960000,10.140000,9.990000e+00
25%,14.025000,14.790000,13.190000,14.250000,12.995000,10.750000,11.470000,14.135000,14.155000,11.310000,...,12.840000,17.030000,1.365000e+01,13.650000,NaN,13.905000,14.710000,13.095000,11.815000,1.224500e+01
50%,379402.000000,11063.000000,143175.000000,247144.000000,158074.000000,35921.000000,615606.000000,297539.000000,72720.000000,78254.000000,...,359433.000000,19208.000000,7.240490e+05,115523.000000,NaN,3979.000000,18768.000000,343767.000000,16818.000000,8.736039e+06
75%,495370.000000,14602.000000,177745.000000,317101.000000,220836.000000,40633.000000,807623.000000,419062.000000,88792.000000,95893.000000,...,481682.000000,23628.000000,9.441460e+05,149817.000000,NaN,4790.000000,24787.000000,468103.500000,22979.500000,1.183519e+07
max,699307.000000,18784.000000,224234.000000,413503.000000,290140.000000,45002.000000,994316.000000,547396.000000,104369.000000,118387.000000,...,654294.000000,29667.000000,1.153795e+06,184091.000000,NaN,5721.000000,30304.000000,622385.000000,29557.000000,1.525103e+07

In [111]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 36 columns):
Items  Description           11 non-null object
Duration                     11 non-null object
Andhra Pradesh               11 non-null float64
Arunachal Pradesh            9 non-null float64
Assam                        9 non-null float64
Bihar                        9 non-null float64
Chhattisgarh                 11 non-null float64
Goa                          9 non-null float64
Gujarat                      9 non-null float64
Haryana                      11 non-null float64
Himachal Pradesh             7 non-null float64
Jammu & Kashmir              9 non-null float64
Jharkhand                    9 non-null float64
Karnataka                    9 non-null float64
Kerala                       9 non-null float64
Madhya Pradesh               11 non-null float64
Maharashtra                  7 non-null float64
Manipur                      7 non-null float64
Meghalaya                    11 non-null float64
Mizoram                      7 non-null float64
Nagaland                     7 non-null float64
Odisha                       11 non-null float64
Punjab                       7 non-null float64
Rajasthan                    7 non-null float64
Sikkim                       9 non-null float64
Tamil Nadu                   11 non-null float64
Telangana                    11 non-null float64
Tripura                      7 non-null float64
Uttar Pradesh                9 non-null float64
Uttarakhand                  9 non-null float64
West Bengal1                 0 non-null float64
Andaman & Nicobar Islands    7 non-null float64
Chandigarh                   9 non-null float64
Delhi                        11 non-null float64
Puducherry                   11 non-null float64
All_India GDP                11 non-null float64
dtypes: float64(34), object(2)
memory usage: 3.2+ KB

In [98]:
df_after_remove =df.drop([5,10], axis=0)

In [99]:
tranposed_df = df_after_remove.transpose()

In [108]:
tranposed_df

,0,1,2,3,4,6,7,8,9
Items Description,GSDP - CURRENT PRICES (` in Crore),GSDP - CURRENT PRICES (` in Crore),GSDP - CURRENT PRICES (` in Crore),GSDP - CURRENT PRICES (` in Crore),GSDP - CURRENT PRICES (` in Crore),(% Growth over previous year),(% Growth over previous year),(% Growth over previous year),(% Growth over previous year)
Duration,2011-12,2012-13,2013-14,2014-15,2015-16,2012-13,2013-14,2014-15,2015-16
Andhra Pradesh,379402,411404,464272,526468,609934,8.43,12.85,13.4,15.85
Arunachal Pradesh,11063,12547,14602,16761,18784,13.41,16.38,14.79,12.07
Assam,143175,156864,177745,198098,224234,9.56,13.31,11.45,13.19
Bihar,247144,282368,317101,373920,413503,14.25,12.3,17.92,10.59
Chhattisgarh,158074,177511,206690,234982,260776,12.3,16.44,13.69,10.98
Goa,42367,38120,35921,40633,45002,-10.02,-5.77,13.12,10.75
Gujarat,615606,724495,807623,895027,994316,17.69,11.47,10.82,11.09
Haryana,297539,347032,400662,437462,485184,16.63,15.45,9.18,10.91
Himachal Pradesh,72720,82820,94764,104369,NaN,13.89,14.42,10.14,NaN
Jammu & Kashmir,78254,87105,95893,100404,118387,11.31,10.09,4.7,17.91
Jharkhand,150918,174724,188567,217107,241955,15.77,7.92,15.14,11.44
Karnataka,603778,691700,817886,921788,1.02707e+06,14.56,18.24,12.7,11.42
Kerala,364048,412313,465041,526002,588337,13.26,12.79,13.11,11.85
Madhya Pradesh,315561,380924,437737,481982,543975,20.71,14.91,10.11,12.86
Maharashtra,1.27297e+06,1.44847e+06,1.64751e+06,1.79212e+06,NaN,13.79,13.74,8.78,NaN
Manipur,12915,13748,16198,18043,NaN,6.45,17.83,11.39,NaN
Meghalaya,19918,21872,22938,24408,26745,9.81,4.87,6.41,9.58
Mizoram,7259,8362,10293,11559,NaN,15.2,23.1,12.3,NaN
Nagaland,11839,13619,16612,18414,NaN,15.03,21.98,10.85,NaN
Odisha,227872,258275,291709,321971,341887,13.34,12.95,10.37,6.19
Punjab,266628,297734,334714,368011,NaN,11.67,12.42,9.95,NaN
Rajasthan,436465,494004,549701,612194,NaN,13.18,11.27,11.37,NaN
Sikkim,11165,12338,13862,15209,16637,10.51,12.35,9.72,9.39
Tamil Nadu,751485,855481,971090,1.09256e+06,1.21267e+06,13.84,13.51,12.51,10.99
Telangana,359433,401493,452186,511178,575631,11.7,12.63,13.05,12.61
Tripura,19208,21663,25593,29667,NaN,12.78,18.14,15.92,NaN
Uttar Pradesh,724049,822903,944146,1.04337e+06,1.1538e+06,13.65,14.73,10.51,10.58
Uttarakhand,115523,131835,149817,161985,184091,14.12,13.64,8.12,13.65
West Bengal1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Andaman & Nicobar Islands,3979,4421,5159,5721,NaN,11.13,16.68,10.89,NaN
Chandigarh,18768,21609,24787,27844,30304,15.14,14.71,12.33,8.84
Delhi,343767,391238,443783,492424,551963,13.81,13.43,10.96,12.09
Puducherry,16818,18875,21870,24089,26533,12.23,15.87,10.14,10.15
All_India GDP,8.73604e+06,9.94664e+06,1.12366e+07,1.24337e+07,1.36753e+07,13.86,12.97,10.65,9.99

In [72]:
sns.barplot(x= 'Items  Description', y='Duration', data =df)

ValueError: Could not interpret input 'Items  Description'